@startuml

' 视频号小店

autonumber

品牌运营 -> 商城后台: 上传资质图片
商城后台 -> 微信API: 调用 上传资质图片 接口
商城后台 -> DBMS: 存储QualificationImage

商城后台 -> 微信API: 获取商品类目（全量）
品牌运营 -> 商城后台: 新增定时任务来全量同步

商城后台 -> 微信API: 获取品牌库（全量）
品牌运营 -> 商城后台: 新增定时任务来全量同步

@enduml
