services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatStoreBundle\AdminMenu: ~

  # 如果确认要使用自动扫描、自动注册，建议尽可能将要扫描的目录路径收缩，不要设置那么大的范围
  WechatStoreBundle\Controller\:
    resource: '../../Controller/'
  WechatStoreBundle\Command\:
    resource: '../../Command/'
  WechatStoreBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  WechatStoreBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatStoreBundle\Repository\:
    resource: '../../Repository/'
  WechatStoreBundle\Service\:
    resource: '../../Service/'
  WechatStoreBundle\Procedure\:
    resource: '../../Procedure/'
