services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatStoreBundle\Controller\:
    resource: '../../Controller/'
  WechatStoreBundle\Command\:
    resource: '../../Command/'
  WechatStoreBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  WechatStoreBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatStoreBundle\Repository\:
    resource: '../../Repository/'
  WechatStoreBundle\Service\:
    resource: '../../Service/'
  WechatStoreBundle\Procedure\:
    resource: '../../Procedure/'

  # 显式注册AdminMenu服务
  wechat_store.admin_menu:
    class: WechatStoreBundle\Service\AdminMenu
    public: true
    arguments:
      - '@Tourze\EasyAdminMenuBundle\Service\LinkGeneratorInterface'
    tags:
      - { name: easy_admin_menu.provider }
